spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/savingstracker
    username: savings-tracker-be
    password: savings-tracker-be
    driver-class-name: org.postgresql.Driver

config:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
  asset:
    api:
      currencyUrl: "https://api.nbp.pl/api/exchangerates/"
      cryptoUrl: "https://api.coincap.io/v2/assets/"
    types:
      - "currency"
      - "cryptocurrency"
